version: '3.8'

services:
  server-mysql:
    image: mysql:8.0.22
    expose: 
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=eolo
    ports:
      - "3306:3306"
    hostname: server-mysql
    container_name: server-mysql
    stdin_open: true
    tty: true
    networks:
      - eolo
  toposervice-mongodb:
    image: mongo:4.4.2-bionic
    expose: 
      - 27017
    ports:
      - "27017:27017"
    hostname: toposervice-mongodb
    container_name: toposervice-mongodb
    stdin_open: true
    tty: true
    networks:
      - eolo
  eolo-rabbitmq:
    image: rabbitmq:3-management-alpine
    expose: 
      - 5672
      - 15672
    ports:
      - "5672:5672"
      - "15672:15672"
    hostname: eolo-rabbitmq
    container_name: eolo-rabbitmq
    stdin_open: true
    tty: true
    networks:
      - eolo

networks:
  eolo:
    driver: bridge 
